### ISSUE TITLE
Log CANbus messages to SD card

### ISSUE THREAD

**Issue by cwljohnson** [QUT-Motorsport/QUTMS_ChassisControllerLogger#3]
Given that #1 and #2 are finished, we want to be able to:
- Log all available information from CANbus to a file on the SD card (w/ time stamps)
- Also if https://github.com/QUT-Motorsport/QUTMS_ChassisController/issues/4 is done, we should be logging in this CSV format

**Comment by CallumJHays** [comment]
I just want to chime in here and say it would probably be better to not write in csv format, and write the CAN struct contents directly instead. There is significant overhead in converting numbers (especially floating point) into ascii format that csv requires. On top of that it massively blows out the amount of bytes we need to read and write through the sdcard spi interface. 

Of course whether we use CSV or some binary protocol doesn't really matter as I understand the blocker with this is probably in the wiring & underlying spi interface to the sd card. The data we actually read and write can be changed later and for now it does make sense to use CSV just for quick verification

**Comment by cwljohnson** [comment]
[canreader.py.txt](https://github.com/QUT-Motorsport/QUTMS_ChassisControllerLogger/files/4084443/canreader.py.txt)


[test.txt](https://github.com/QUT-Motorsport/QUTMS_ChassisControllerLogger/files/4084440/test.txt)

sample log file and simple python script to read it
